FoodSync/urls.py
from django.urls import path, include
from FoodSync import views
from recipe import views as recipe_views
from django.contrib import admin

urlpatterns = [
    # path('', views.index, name='index'),
    path("recipe/", include("recipe.urls")),
    path("homepage/", include("homepage.urls")),
    path("groceryStore/", include("groceryStore.urls")),
    path("", include("users.urls")),
    path("admin/", admin.site.urls),
    path("store/", include('store.urls')),
    path("userProfilePage/", include("userProfilePage.urls")),
    path("addToCart/", recipe_views.add_to_cart, name="add_to_cart"),
    path("fetch-cart-data/", recipe_views.fetch_cart_data, name="fetch_cart_data"),
    path("update_cart/", recipe_views.update_cart, name="update_cart"),
    path(
        "check_session_variable/",
        recipe_views.check_session_variable,
        name="check_session_variable",
    ),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"

urlpatterns = [
    path("", views.homepage, name="homepage"),
]

recipe/urls.py
from django.urls import path
from . import views

app_name = "recipe"

urlpatterns = [
    path("recipe/<int:recipe_id>/", views.recipe_info, name="recipe"),
]

store/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import orders_view, order_items, change_order_status, login_redirect_admin, admin_login

urlpatterns = [
    # path("login/", auth_views.LoginView.as_view(template_name='store/login.html'), name='login'),
    path('adminLogin/', admin_login, name='admin_login'),
    path('orders/', orders_view, name='orders'),
    path("", login_redirect_admin, name='login_admin'),
    path('order-items/<int:order_id>/', order_items, name='order_items'),
    path('change-order-status/<int:order_id>/', change_order_status, name='change_order_status'),
]

homepage/views.py
import requests
import os

from django.shortcuts import render

from utils.homepage_utils import homepage_recipes


def homepage(request):
    preferences_updated = request.session.pop("preferences_updated", False)
    check_user_preferences = request.session.get("check_user_preferences")
    # Check if preferences have been updated
    if preferences_updated:
        homepage_recipes(request)
    if request.session.get("homepage_recipes_info"):
        recipes_info = request.session.get("homepage_recipes_info")
        response = render(request, "homepage/homepage.html", {"recipes": recipes_info})
    else:
        homepage_recipes(request)
        recipes_info = request.session.get("homepage_recipes_info")
        response = render(
            request,
            "homepage/homepage.html",
            {"recipes": recipes_info, "check_user_preferences": check_user_preferences},
        )

    response["Cache-Control"] = "no-store"
    return response

homepage/templates/homepage/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FoodSync</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<style>
    .card {
        margin-bottom: 20px;
    }
    .badge:after{
        content:attr(value);
        font-size:12px;
        color: #fff;
        background: red;
        border-radius:50%;
        padding: 0 5px;
        position:relative;
        left:-8px;
        top:-10px;
        opacity:0.9;
    }
</style>
<style>
    .badge-cart {
        font-size: 0.75rem;
        padding: 0.25em 0.4em;
        border-radius: 0.375rem;
        background-color: #007bff;
        top: -10px;
        right: -10px;
    }

      /* Styling for cart overlay */
    .cart-overlay {
      display: none;
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.5); /* Semi-transparent background */
      z-index: 999; /* Ensure the overlay appears above other content */
    }
    
    .cart-content {
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: white;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.3); /* Drop shadow effect */
    }
    
    </style>
<body>
    <div class="sticky-top">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="/homepage">FoodSync</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/homepage">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/preferences">Preferences</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/userProfilePage">Profile</a>
                  </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item position-relative">
                        <i class="fa badge fa-lg" style="font-size:24px; color: #000;" id="cart-button">&#xf07a;</i>
                    </li>
                </ul>
                <span class="navbar-text">
                    {% if user.is_authenticated%}
                        <button type="button" class="d-flex btn btn-primary btn-circle btn-sm dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                            <!-- {{ user.socialaccount_set.all.0.extra_data.name}} -->
                            {% if user.socialaccount_set.all %}
                                {{ user.socialaccount_set.all.0.extra_data.name }}
                            {% else %}
                                {{ user.username }}
                            {% endif %}
                        </button>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
                            <a type="a" href="{% url 'userProfilePage' %}">User Profile</a>
                            <!-- <form method="post" action="{% url 'account_logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Logout</button>
                            </form> -->
                            <form method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Logout</button>
                            </form>
                        </div>
                    {% else %}
                        <a href="/">Please login</a>
                    {% endif %}
                </span>
              </div>
            </div>
          </nav>
        </div>
    <br><br><br>
    <div class="container">
        {% if not request.session.check_user_preferences %}
            <div class="alert alert-success" role="alert">
                Please update your preferences to get personalized recipes. <a href="{% url 'preferences' %}" class="alert-link">Update preferences</a>.
            </div>
        {% endif %}

        <div class="row">
            {% for recipe in recipes.recipes %}
                <div class="col-md-3">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ recipe.image }}" alt="{{ recipe.title }}" class="img-fluid">
                        <div class="card-body">
                        <h5 class="card-title">{{recipe.title}}</h5>
                        <p class="card-text">Ready in {{recipe.readyInMinutes}} minutes. </p>
                        <a href="{% url 'recipe:recipe' recipe_id=recipe.id %}" class="btn btn-primary">Prepare this recipe</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
    <div id="cart-overlay" class="cart-overlay">
        <div class="cart-content">
            <h2>Cart</h2>
            <div id="cart-items">
                <!-- Cart items will be popdivated dynamically -->
            </div>
        </div>
    </div>
</body>

<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/af52a1a454.js" crossorigin="anonymous"></script>
<script src="{% static 'js/cart.js' %}"></script>
</html>